repos:
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.23.3
  hooks:
  - id: check-jsonschema
    files: "^vulns/[a-z0-9_-]+/.+\\.yaml"
    args: [--schemafile, "https://raw.githubusercontent.com/ossf/osv-schema/refs/tags/v1.6.7/validation/schema.json"]
- repo: https://github.com/jackdewinter/pymarkdown
  rev: v0.9.25
  hooks:
    - id: pymarkdown
      args:
      - -d
      - MD013
      - scan
